// UI related
export const LOADING = "LOADING";
export const LOADED = "LOADED";
export const TOGGLE_LOADER = "TOGGLE_LOADER"

// Menu Related
export const TOGGLE_SIDE_MENU = "TOGGLE_SIDE_MENU";

// Modal Related
export const TOGGLE_MODAL = "TOGGLE_MODAL";

// Auth Related
export const MOUNT_LOGIN_MODAL = "MOUNT_LOGIN_MODAL";
export const UNMOUNT_LOGIN_MODAL = "UNMOUNT_LOGIN_MODAL";
export const HANDLE_LOGIN = "HANDLE_LOGIN";
export const HANDLE_LOGOUT = "HANDLE_LOGOUT";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_UNSUCCESSFUL = "LGOIN_UNSUCCESSFUL";
export const LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL";
export const LOGOUT_UNSUCCESSFUL = "LOGOUT_UNSUCCESSFUL";
export const CLEAR_EMAIL_ERROR = "CLEAR_EMAIL_ERROR";
export const CLEAR_PASSWORD_ERROR = "CLEAR_PASSWORD_ERROR";

// Login Related
export const MOUNT_LOGIN_CONTAINER = "MOUNT_LOGIN_CONTAINER";
export const UNMOUNT_LOGIN_CONTAINER = "UNMOUNT_LOGIN_CONTAINER";
export const HANDLE_SIGNIN = "HANDLE_SIGNIN";
export const STORE_PREVIOUS_LOCATION = "STORE_PREVIOUS_LOCATION";

//Home Related
export const MOUNT_HOME_CONTAINER = "MOUNT_HOME_CONTAINER";
export const UNMOUNT_HOME_CONTAINER = "UNMOUNT_HOME_CONTAINER";

// Key Related
export const GENERATE_KEYS = "GENERATE_KEYS";

// Loaders Related
export const LOAD_HOSPITAL_STAFF = "LOAD_HOSPITAL_STAFF";
export const LOAD_PATIENTS = "LOAD_PATIENTS";
export const LOAD_HOSPITALS = "LOAD_HOSPITALS";
export const LOAD_HOSPITAL = "LOAD_HOSPITAL";
export const LOAD_HEALTHCARE_SYSTEM = "LOAD_HEALTHCARE_SYSTEM";
export const LOAD_UNITS = "LOAD_UNITS";
export const LOAD_HOSPITAL_STAFF_TYPES = "LOAD_HOSPITAL_STAFF_TYPES";
export const LOAD_HOSPITAL_ADMINISTRATORS = "LOAD_HOSPITAL_ADMINISTRATORS";
export const LOAD_HOSPIATL_STAFF = "LOAD_HOSPITAL_STAFF";
export const LOAD_HOSPITAL_SHIFTS = "LOAD_HOSPITAL_SHIFTS";
export const LOAD_HOSPITAL_SHIFT_ASSIGNMENTS = "LOAD_HOSPITAL_SHIFT_ASSIGNMENTS";
export const LOAD_ROOM_ATTRIBUTES = "LOAD_ROOM_ATTRIBUTES";
export const LOAD_ROOMS = "LOAD_ROOMS";
export const LOAD_PATIENT_TRANSITIONS = "LOAD_PATIENT_TRANSITIONS";
export const LOAD_ACUITY_LEVEL_FORMS = "LOAD_ACUITY_LEVEL_FORMS";
export const LOAD_ACUITY_LEVEL_TYPES = "LOAD_ACUITY_LEVEL_TYPES";
export const LOAD_ACUITY_LEVEL_CATEGORIES = "LOAD_ACUITY_LEVEL_CATEGORIES";
export const LOAD_ACUITY_LEVEL_OPTIONS = "LOAD_ACUITY_LEVEL_OPTIONS";
export const LOAD_ACUITY_LEVEL_OPTION_ASSOCIATIONS = "LOAD_ACUITY_LEVEL_OPTION_ASSOCIATIONS";
export const LOAD_ACUITY_LEVELS = "LOAD_ACUITY_LEVELS";

// GET RESPONSE Related
export const GET_RESPONSE_PATIENTS = "GET_RESPONSE_PATIENTS";
export const GET_RESPONSE_HOSPITALS = "GET_RESPONSE_HOSPITALS";
export const GET_RESPONSE_HOSPITAL = "GET_RESPONSE_HOSPITAL";
export const GET_RESPONSE_HEALTHCARE_SYSTEM = "GET_RESPONSE_HEALTHCARE_SYSTEM";
export const GET_RESPONSE_UNITS = "GET_RESPONSE_UNITS";
export const GET_RESPONSE_HOSPITAL_STAFF_TYPES = "GET_RESPONSE_HOSPITAL_STAFF_TYPES";
export const GET_RESPONSE_HOSPITAL_ADMINISTRATORS = "GET_RESPONSE_HOSPITAL_ADMINISTRATORS";
export const GET_RESPONSE_HOSPITAL_STAFF = "GET_RESPONSE_HOSPITAL_STAFF";
export const GET_RESPONSE_HOSPITAL_SHIFTS = "GET_RESPONSE_HOSPITAL_SHIFTS";
export const GET_RESPONSE_HOSPITAL_SHIFT_ASSIGNMENTS = "GET_RESPONSE_HOSPITAL_SHIFT_ASSIGNMENTS";
export const GET_RESPONSE_ROOM_ATTRIBUTES = "GET_RESPONSE_ROOM_ATTRIBUTES";
export const GET_RESPONSE_ROOMS = "GET_RESPONSE_ROOMS";
export const GET_RESPONSE_PATIENT_TRANSITIONS = "GET_RESPONSE_PATIENT_TRANSITIONS";
export const GET_RESPONSE_ACUITY_LEVEL_FORMS = "GET_RESPONSE_ACUITY_LEVEL_FORMS";
export const GET_RESPONSE_ACUITY_LEVEL_TYPES = "GET_RESPONSE_ACUITY_LEVEL_TYPES";
export const GET_RESPONSE_ACUITY_LEVEL_CATEGORIES = "GET_RESPONSE_ACUITY_LEVEL_CATEGORIES";
export const GET_RESPONSE_ACUITY_LEVEL_OPTIONS = "GET_RESPONSE_ACUITY_LEVEL_OPTIONS";
export const GET_RESPONSE_ACUITY_LEVEL_OPTION_ASSOCIATIONS = "GET_RESPONSE_ACUITY_LEVEL_OPTION_ASSOCIATIONS";
export const GET_RESPONSE_ACUITY_LEVELS = "GET_RESPONSE_ACUITY_LEVELS";

// POST Related
export const POST_EMAIL_LIST_SIGN_UP = "POST_EMAIL_LIST_SIGN_UP";

// POST Response Related
export const POST_RESPONSE_EMAIL_LIST_SIGN_UP_SUCCESSFUL = "POST_RESPONSE_EMAIL_LIST_SIGN_UP_SUCCESSFUL";
export const POST_RESPONSE_EMAIL_LIST_SIGN_UP_ERROR = "POST_RESPONSE_EMAIL_LIST_SIGN_UP_ERROR";
